#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
	ln -f -s /usr/share/mydesk/mydesk /usr/bin/mydesk

	if [ "systemd" == "$INITSYS" ]; then

		if [ -e /etc/systemd/system/mydesk.service ]; then
			rm /etc/systemd/system/mydesk.service /usr/lib/systemd/system/mydesk.service /usr/lib/systemd/user/mydesk.service >/dev/null  2>&1
		fi
		mkdir -p /usr/lib/systemd/system/
		cp /usr/share/mydesk/files/systemd/mydesk.service /usr/lib/systemd/system/mydesk.service
		# try fix error in Ubuntu 18.04
		# Failed to reload mydesk.service: Unit mydesk.service is not loaded properly: Exec format error.
		# /usr/lib/systemd/system/mydesk.service:10: Executable path is not absolute: pkill -f "mydesk --"
		if [ -e /usr/bin/pkill ]; then
			sed -i "s|pkill|/usr/bin/pkill|g" /usr/lib/systemd/system/mydesk.service
		fi
		systemctl daemon-reload
		systemctl enable mydesk
		systemctl start mydesk
	fi
fi
